# Generated by Django 6.0.5 on 2026-05-28 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('cedula', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('nombre_completo', models.CharField(max_length=150)),
                ('edad', models.IntegerField()),
                ('genero', models.CharField(max_length=20)),
                ('ciudad', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroClinico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_visita', models.DateField()),
                ('presion_arterial', models.CharField(max_length=20)),
                ('nivel_azucar', models.FloatField()),
                ('colesterol', models.IntegerField()),
                ('diagnostico', models.TextField()),
                ('prediccion_riesgo', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='etl.paciente')),
            ],
        ),
    ]
