# Generated by Django 6.0.5 on 2026-06-01 02:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('sexo', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroClinico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.FloatField()),
                ('altura', models.FloatField()),
                ('imc', models.FloatField()),
                ('presion_sistolica', models.IntegerField()),
                ('presion_diastolica', models.IntegerField()),
                ('frecuencia_cardiaca', models.IntegerField()),
                ('glucosa', models.FloatField()),
                ('colesterol', models.IntegerField()),
                ('saturacion_oxigeno', models.FloatField()),
                ('temperatura', models.FloatField()),
                ('antecedentes_familiares', models.TextField()),
                ('fumador', models.BooleanField()),
                ('consumo_alcohol', models.BooleanField()),
                ('actividad_fisica', models.CharField(max_length=50)),
                ('diagnostico_preliminar', models.TextField()),
                ('riesgo_enfermedad', models.CharField(max_length=50)),
                ('fecha_consulta', models.DateField()),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='etl.paciente')),
            ],
        ),
    ]
