# Generated by Django 6.0.5 on 2026-06-10 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("etl", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ETLLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_ejecucion", models.DateTimeField(auto_now_add=True)),
                ("registros_procesados", models.IntegerField(default=0)),
                ("registros_fallidos", models.IntegerField(default=0)),
                (
                    "tiempo_ejecucion",
                    models.FloatField(default=0.0, help_text="Segundos"),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("exitoso", "Exitoso"),
                            ("fallido", "Fallido"),
                            ("en_proceso", "En Proceso"),
                        ],
                        default="en_proceso",
                        max_length=20,
                    ),
                ),
                ("archivo_fuente", models.CharField(blank=True, max_length=255)),
                ("mensaje_error", models.TextField(blank=True)),
                ("log_detalle", models.TextField(blank=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Log ETL",
                "verbose_name_plural": "Logs ETL",
                "ordering": ["-fecha_ejecucion"],
            },
        ),
    ]
