# Generated by Django 6.0.5 on 2026-06-10 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ModeloML",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_entrenamiento", models.DateTimeField(auto_now_add=True)),
                ("algoritmo", models.CharField(max_length=100)),
                ("accuracy", models.FloatField()),
                ("precision", models.FloatField()),
                ("recall", models.FloatField()),
                ("f1_score", models.FloatField()),
                ("total_registros", models.IntegerField()),
                ("activo", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["-fecha_entrenamiento"],
            },
        ),
    ]
